export interface CountryInfo {
  code: string;
  name: string;
  nameFr: string;
  currency: string;
  currencySymbol: string;
  phonePrefix: string;
  timezone: string;
  vatRate: number;
  isOhada: boolean;
  regions?: Record<string, string[]>;
}

export const COUNTRIES: CountryInfo[] = [
  {
    code: 'CM', name: 'Cameroon', nameFr: 'Cameroun',
    currency: 'XAF', currencySymbol: 'FCFA', phonePrefix: '+237',
    timezone: 'Africa/Douala', vatRate: 19.25, isOhada: true,
    regions: {
      'Littoral': ['Douala', 'Edéa', 'Nkongsamba'],
      'Centre': ['Yaoundé', 'Bafia', 'Mbalmayo'],
      'Ouest': ['Bafoussam', 'Dschang', 'Foumban'],
      'Nord-Ouest': ['Bamenda', 'Kumbo'],
      'Sud-Ouest': ['Buea', 'Limbe', 'Kumba'],
      'Adamaoua': ['Ngaoundéré', 'Meiganga'],
      'Nord': ['Garoua', 'Guider'],
      'Extrême-Nord': ['Maroua', 'Kousséri'],
      'Est': ['Bertoua', 'Abong-Mbang'],
      'Sud': ['Ebolowa', 'Sangmélima'],
    },
  },
  {
    code: 'SN', name: 'Senegal', nameFr: 'Sénégal',
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+221',
    timezone: 'Africa/Dakar', vatRate: 18, isOhada: true,
    regions: {
      'Dakar': ['Dakar', 'Pikine', 'Guédiawaye'],
      'Thiès': ['Thiès', 'Mbour', 'Tivaouane'],
      'Saint-Louis': ['Saint-Louis', 'Richard-Toll'],
      'Ziguinchor': ['Ziguinchor', 'Bignona'],
      'Kaolack': ['Kaolack', 'Nioro du Rip'],
      'Diourbel': ['Diourbel', 'Touba'],
      'Tambacounda': ['Tambacounda'],
      'Matam': ['Matam'],
      'Kolda': ['Kolda', 'Vélingara'],
      'Sédhiou': ['Sédhiou'],
      'Kaffrine': ['Kaffrine'],
      'Louga': ['Louga', 'Linguère'],
      'Fatick': ['Fatick', 'Sokone'],
    },
  },
  {
    code: 'CI', name: "Côte d'Ivoire", nameFr: "Côte d'Ivoire",
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+225',
    timezone: 'Africa/Abidjan', vatRate: 18, isOhada: true,
    regions: {
      'Abidjan': ['Abidjan', 'Abobo', 'Yopougon'],
      'Bouaké': ['Bouaké', 'Béoumi'],
      'Yamoussoukro': ['Yamoussoukro'],
      'Korhogo': ['Korhogo', 'Ferkessédougou'],
      'San-Pédro': ['San-Pédro', 'Sassandra'],
      'Daloa': ['Daloa', 'Issia'],
      'Man': ['Man', 'Danangé'],
      'Gagnoa': ['Gagnoa', 'Oumé'],
    },
  },
  {
    code: 'NG', name: 'Nigeria', nameFr: 'Nigéria',
    currency: 'NGN', currencySymbol: '₦', phonePrefix: '+234',
    timezone: 'Africa/Lagos', vatRate: 7.5, isOhada: false,
    regions: {
      'Lagos': ['Lagos', 'Ikeja', 'Badagry'],
      'Abuja FCT': ['Abuja'],
      'Kano': ['Kano', 'Wudil'],
      'Rivers': ['Port Harcourt', 'Obio-Akpor'],
      'Oyo': ['Ibadan', 'Ogbomosho'],
      'Kaduna': ['Kaduna', 'Zaria'],
      'Enugu': ['Enugu', 'Nsukka'],
      'Ogun': ['Abeokuta', 'Sagamu'],
      'Anambra': ['Onitsha', 'Awka'],
      'Delta': ['Warri', 'Asaba'],
    },
  },
  {
    code: 'KE', name: 'Kenya', nameFr: 'Kenya',
    currency: 'KES', currencySymbol: 'KSh', phonePrefix: '+254',
    timezone: 'Africa/Nairobi', vatRate: 16, isOhada: false,
    regions: {
      'Nairobi': ['Nairobi', 'Westlands', 'Embakasi'],
      'Mombasa': ['Mombasa', 'Kisauni'],
      'Kisumu': ['Kisumu', 'Maseno'],
      'Nakuru': ['Nakuru', 'Naivasha'],
      'Eldoret': ['Eldoret', 'Kitale'],
      'Nyeri': ['Nyeri', 'Karatina'],
      'Meru': ['Meru'],
      'Kakamega': ['Kakamega', 'Bungoma'],
    },
  },
  {
    code: 'GH', name: 'Ghana', nameFr: 'Ghana',
    currency: 'GHS', currencySymbol: '₵', phonePrefix: '+233',
    timezone: 'Africa/Accra', vatRate: 12.5, isOhada: false,
    regions: {
      'Greater Accra': ['Accra', 'Tema', 'Madina'],
      'Ashanti': ['Kumasi', 'Obuasi'],
      'Western': ['Takoradi', 'Sekondi'],
      'Eastern': ['Koforidua', 'Nkawkaw'],
      'Central': ['Cape Coast', 'Winneba'],
      'Volta': ['Ho', 'Kpando'],
      'Northern': ['Tamale', 'Savelugu'],
      'Bono': ['Sunyani', 'Berekum'],
    },
  },
  {
    code: 'TZ', name: 'Tanzania', nameFr: 'Tanzanie',
    currency: 'TZS', currencySymbol: 'TSh', phonePrefix: '+255',
    timezone: 'Africa/Dar_es_Salaam', vatRate: 18, isOhada: false,
    regions: {
      'Dar es Salaam': ['Dar es Salaam', 'Kinondoni'],
      'Mwanza': ['Mwanza'],
      'Arusha': ['Arusha'],
      'Zanzibar': ['Zanzibar City'],
      'Dodoma': ['Dodoma'],
      'Mbeya': ['Mbeya', 'Kyela'],
      'Tanga': ['Tanga', 'Muheza'],
      'Morogoro': ['Morogoro', 'Kilosa'],
    },
  },
  {
    code: 'ET', name: 'Ethiopia', nameFr: 'Éthiopie',
    currency: 'ETB', currencySymbol: 'Br', phonePrefix: '+251',
    timezone: 'Africa/Addis_Ababa', vatRate: 15, isOhada: false,
    regions: {
      'Addis Ababa': ['Addis Ababa'],
      'Oromia': ['Dire Dawa', 'Adama'],
      'Amhara': ['Bahir Dar', 'Gondar'],
      'Tigray': ['Mekelle', 'Adwa'],
      'Sidama': ['Hawassa'],
      'Somali': ['Jijiga'],
    },
  },
  {
    code: 'ZA', name: 'South Africa', nameFr: 'Afrique du Sud',
    currency: 'ZAR', currencySymbol: 'R', phonePrefix: '+27',
    timezone: 'Africa/Johannesburg', vatRate: 15, isOhada: false,
    regions: {
      'Gauteng': ['Johannesburg', 'Pretoria', 'Ekurhuleni'],
      'Western Cape': ['Cape Town', 'Stellenbosch'],
      'KwaZulu-Natal': ['Durban', 'Pietermaritzburg'],
      'Eastern Cape': ['Port Elizabeth', 'East London'],
      'Free State': ['Bloemfontein', 'Welkom'],
      'Mpumalanga': ['Mbombela', 'Witbank'],
      'Limpopo': ['Polokwane', 'Tzaneen'],
      'North West': ['Mahikeng', 'Rustenburg'],
      'Northern Cape': ['Kimberley', 'Upington'],
    },
  },
  {
    code: 'EG', name: 'Egypt', nameFr: 'Égypte',
    currency: 'EGP', currencySymbol: 'E£', phonePrefix: '+20',
    timezone: 'Africa/Cairo', vatRate: 14, isOhada: false,
    regions: {
      'Cairo': ['Cairo', 'Giza', 'New Cairo'],
      'Alexandria': ['Alexandria'],
      'Luxor': ['Luxor'],
      'Aswan': ['Aswan'],
      'Suez': ['Suez', 'Ismailia'],
      'Port Said': ['Port Said'],
      'Red Sea': ['Hurghada', 'Sharm El-Sheikh'],
    },
  },
  {
    code: 'MA', name: 'Morocco', nameFr: 'Maroc',
    currency: 'MAD', currencySymbol: 'MAD', phonePrefix: '+212',
    timezone: 'Africa/Casablanca', vatRate: 20, isOhada: false,
    regions: {
      'Casablanca-Settat': ['Casablanca', 'Mohammedia'],
      'Rabat-Salé': ['Rabat', 'Salé'],
      'Marrakech-Safi': ['Marrakech', 'Safi'],
      'Fès-Meknès': ['Fès', 'Meknès'],
      'Tanger-Tétouan': ['Tanger', 'Tétouan'],
      'Souss-Massa': ['Agadir', 'Inezgane'],
      'Oriental': ['Oujda', 'Nador'],
    },
  },
  {
    code: 'TN', name: 'Tunisia', nameFr: 'Tunisie',
    currency: 'TND', currencySymbol: 'DT', phonePrefix: '+216',
    timezone: 'Africa/Tunis', vatRate: 19, isOhada: false,
    regions: {
      'Tunis': ['Tunis', 'La Marsa', 'Le Bardo'],
      'Sfax': ['Sfax'],
      'Sousse': ['Sousse', 'Monastir'],
      'Ariana': ['Ariana', 'Ettadhamen'],
      'Nabeul': ['Nabeul', 'Hammamet'],
      'Bizerte': ['Bizerte', 'Menzel Bourguiba'],
    },
  },
  {
    code: 'DZ', name: 'Algeria', nameFr: 'Algérie',
    currency: 'DZD', currencySymbol: 'DA', phonePrefix: '+213',
    timezone: 'Africa/Algiers', vatRate: 19, isOhada: false,
    regions: {
      'Alger': ['Alger', 'Bab Ezzouar', 'Hydra'],
      'Oran': ['Oran', 'Es Sénia'],
      'Constantine': ['Constantine'],
      'Annaba': ['Annaba', 'El Hadjar'],
      'Blida': ['Blida', 'Boufarik'],
      'Sétif': ['Sétif', 'El Eulma'],
      'Tlemcen': ['Tlemcen', 'Maghnia'],
    },
  },
  {
    code: 'CD', name: 'DR Congo', nameFr: 'RD Congo',
    currency: 'CDF', currencySymbol: 'FC', phonePrefix: '+243',
    timezone: 'Africa/Kinshasa', vatRate: 16, isOhada: true,
    regions: {
      'Kinshasa': ['Kinshasa'],
      'Katanga': ['Lubumbashi', 'Likasi'],
      'Nord-Kivu': ['Goma', 'Butembo'],
      'Sud-Kivu': ['Bukavu', 'Uvira'],
      'Kasaï': ['Mbuji-Mayi', 'Mwene-Ditu'],
      'Équateur': ['Mbandaka'],
      'Orientale': ['Kisangani', 'Bunia'],
    },
  },
  {
    code: 'MG', name: 'Madagascar', nameFr: 'Madagascar',
    currency: 'MGA', currencySymbol: 'Ar', phonePrefix: '+261',
    timezone: 'Indian/Antananarivo', vatRate: 20, isOhada: false,
    regions: {
      'Analamanga': ['Antananarivo'],
      'Atsinanana': ['Toamasina'],
      'Vakinankaratra': ['Antsirabe'],
      'Diana': ['Antsiranana'],
      'Boeny': ['Mahajanga'],
      'Atsimo-Andrefana': ['Toliara'],
      'Fianarantsoa': ['Fianarantsoa'],
    },
  },
  {
    code: 'AO', name: 'Angola', nameFr: 'Angola',
    currency: 'AOA', currencySymbol: 'Kz', phonePrefix: '+244',
    timezone: 'Africa/Luanda', vatRate: 14, isOhada: false,
    regions: {
      'Luanda': ['Luanda'],
      'Huambo': ['Huambo'],
      'Benguela': ['Lobito', 'Benguela'],
      'Huíla': ['Lubango'],
      'Cabinda': ['Cabinda'],
      'Malanje': ['Malanje'],
    },
  },
  {
    code: 'MZ', name: 'Mozambique', nameFr: 'Mozambique',
    currency: 'MZN', currencySymbol: 'MT', phonePrefix: '+258',
    timezone: 'Africa/Maputo', vatRate: 17, isOhada: false,
    regions: {
      'Maputo': ['Maputo'],
      'Beira': ['Beira', 'Dondo'],
      'Nampula': ['Nampula', 'Nacala-Porto'],
      'Tete': ['Tete', 'Moatize'],
      'Quelimane': ['Quelimane'],
      'Pemba': ['Pemba'],
    },
  },
  {
    code: 'UG', name: 'Uganda', nameFr: 'Ouganda',
    currency: 'UGX', currencySymbol: 'USh', phonePrefix: '+256',
    timezone: 'Africa/Kampala', vatRate: 18, isOhada: false,
    regions: {
      'Central': ['Kampala', 'Wakiso'],
      'Eastern': ['Jinja', 'Mbale'],
      'Western': ['Mbarara', 'Fort Portal'],
      'Northern': ['Gulu', 'Lira'],
      'Gulu': ['Gulu', 'Kitgum'],
    },
  },
  {
    code: 'RW', name: 'Rwanda', nameFr: 'Rwanda',
    currency: 'RWF', currencySymbol: 'RF', phonePrefix: '+250',
    timezone: 'Africa/Kigali', vatRate: 18, isOhada: false,
    regions: {
      'Kigali': ['Kigali', 'Nyarugenge'],
      'Southern': ['Huye', 'Nyanza'],
      'Northern': ['Musanze', 'Gicumbi'],
      'Eastern': ['Rwamagana', 'Kayonza'],
      'Western': ['Karongi', 'Rubavu'],
    },
  },
  {
    code: 'GA', name: 'Gabon', nameFr: 'Gabon',
    currency: 'XAF', currencySymbol: 'FCFA', phonePrefix: '+241',
    timezone: 'Africa/Libreville', vatRate: 18, isOhada: true,
    regions: {
      'Estuaire': ['Libreville', 'Owendo'],
      'Haut-Ogooué': ['Franceville'],
      'Ogooué-Maritime': ['Port-Gentil'],
      'Moyen-Ogooué': ['Lambaréné'],
      'Ngounié': ['Mouila'],
      'Ogooué-Ivindo': ['Oyem'],
    },
  },
  {
    code: 'BJ', name: 'Benin', nameFr: 'Bénin',
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+229',
    timezone: 'Africa/Porto-Novo', vatRate: 18, isOhada: true,
    regions: {
      'Littoral': ['Cotonou'],
      'Ouémé': ['Porto-Novo'],
      'Atlantique': ['Allada', 'Ouidah'],
      'Borgou': ['Parakou', 'Kandi'],
      'Zou': ['Abomey', 'Bohicon'],
      'Mono': ['Lokossa', 'Dogbo'],
    },
  },
  {
    code: 'TG', name: 'Togo', nameFr: 'Togo',
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+228',
    timezone: 'Africa/Lome', vatRate: 18, isOhada: true,
    regions: {
      'Maritime': ['Lomé', 'Tsévié'],
      'Savanes': ['Dapaong'],
      'Centrale': ['Sokodé'],
      'Plateaux': ['Atakpamé', 'Kpalimé'],
      'Kara': ['Kara', 'Bassar'],
    },
  },
  {
    code: 'BF', name: 'Burkina Faso', nameFr: 'Burkina Faso',
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+226',
    timezone: 'Africa/Ouagadougou', vatRate: 18, isOhada: true,
    regions: {
      'Centre': ['Ouagadougou'],
      'Hauts-Bassins': ['Bobo-Dioulasso'],
      'Cascades': ['Banfora'],
      'Boucle du Mouhoun': ['Dédougou'],
      'Nord': ['Ouahigouya'],
      'Est': ['Fada N\'Gourma'],
      'Sud-Ouest': ['Gaoua'],
      'Centre-Ouest': ['Koudougou'],
      'Centre-Est': ['Tenkodogo'],
      'Plateau-Central': ['Ziniaré'],
    },
  },
  {
    code: 'ML', name: 'Mali', nameFr: 'Mali',
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+223',
    timezone: 'Africa/Bamako', vatRate: 18, isOhada: true,
    regions: {
      'Bamako': ['Bamako'],
      'Sikasso': ['Sikasso'],
      'Ségou': ['Ségou'],
      'Kayes': ['Kayes', 'Kita'],
      'Mopti': ['Mopti', 'Sévaré'],
      'Tombouctou': ['Tombouctou'],
      'Gao': ['Gao'],
      'Taoudénit': ['Taoudénit'],
    },
  },
  {
    code: 'NE', name: 'Niger', nameFr: 'Niger',
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+227',
    timezone: 'Africa/Niamey', vatRate: 19, isOhada: true,
    regions: {
      'Niamey': ['Niamey'],
      'Agadez': ['Agadez', 'Arlit'],
      'Zinder': ['Zinder', 'Mirriah'],
      'Maradi': ['Maradi'],
      'Tillabéri': ['Tillabéri', 'Say'],
      'Diffa': ['Diffa'],
      'Dosso': ['Dosso', 'Dogondoutchi'],
    },
  },
  {
    code: 'GN', name: 'Guinea', nameFr: 'Guinée',
    currency: 'GNF', currencySymbol: 'FG', phonePrefix: '+224',
    timezone: 'Africa/Conakry', vatRate: 18, isOhada: true,
    regions: {
      'Conakry': ['Conakry'],
      'Haute Guinée': ['Kankan'],
      'Moyenne Guinée': ['Labé'],
      'Guinée Forestière': ['Nzérékoré'],
      'Basse Guinée': ['Kindia', 'Boké'],
    },
  },
  {
    code: 'CG', name: 'Republic of the Congo', nameFr: 'Congo',
    currency: 'XAF', currencySymbol: 'FCFA', phonePrefix: '+242',
    timezone: 'Africa/Brazzaville', vatRate: 18.9, isOhada: true,
    regions: {
      'Brazzaville': ['Brazzaville'],
      'Pointe-Noire': ['Pointe-Noire'],
      'Kouilou': ['Kouilou'],
      'Cuvette': ['Owando'],
      'Sangha': ['Sembé'],
      'Likouala': ['Impfondo'],
      'Pool': ['Kinkala'],
    },
  },
  {
    code: 'TD', name: 'Chad', nameFr: 'Tchad',
    currency: 'XAF', currencySymbol: 'FCFA', phonePrefix: '+235',
    timezone: 'Africa/Ndjamena', vatRate: 18, isOhada: true,
    regions: {
      'N\'Djamena': ['N\'Djamena'],
      'Hadjer-Lamis': ['Massakory'],
      'Logone Oriental': ['Doba'],
      'Mayo-Kebbi': ['Bongor'],
      'Salamat': ['Am Timan'],
      'Kanem': ['Mao'],
      'Lac': ['Bol'],
      'Batha': ['Ati'],
    },
  },
  {
    code: 'CF', name: 'Central African Republic', nameFr: 'République centrafricaine',
    currency: 'XAF', currencySymbol: 'FCFA', phonePrefix: '+236',
    timezone: 'Africa/Bangui', vatRate: 19, isOhada: true,
    regions: {
      'Bangui': ['Bangui'],
      'Ouham': ['Bossangoa'],
      'Ouham-Pendé': ['Bozoum'],
      'Haute-Kotto': ['Bria'],
      'Lobaye': ['Mbaïki'],
      'Nana-Mambéré': ['Bouar'],
    },
  },
  {
    code: 'GQ', name: 'Equatorial Guinea', nameFr: 'Guinée équatoriale',
    currency: 'XAF', currencySymbol: 'FCFA', phonePrefix: '+240',
    timezone: 'Africa/Malabo', vatRate: 15, isOhada: true,
    regions: {
      'Bioko Norte': ['Malabo'],
      'Bioko Sur': ['Luba'],
      'Continental': ['Bata', 'Mbini'],
      'Wele-Nzas': ['Ebebiyin'],
    },
  },
  {
    code: 'KM', name: 'Comoros', nameFr: 'Comores',
    currency: 'KMF', currencySymbol: 'FC', phonePrefix: '+269',
    timezone: 'Indian/Comoro', vatRate: 10, isOhada: false,
    regions: {
      'Grande Comore': ['Moroni'],
      'Anjouan': ['Mutsamudu'],
      'Mohéli': ['Fomboni'],
    },
  },
  {
    code: 'DJ', name: 'Djibouti', nameFr: 'Djibouti',
    currency: 'DJF', currencySymbol: 'FDj', phonePrefix: '+253',
    timezone: 'Africa/Djibouti', vatRate: 10, isOhada: false,
    regions: {
      'Djibouti': ['Djibouti', 'Arta'],
      'Ali Sabieh': ['Ali Sabieh'],
      'Dikhil': ['Dikhil'],
      'Tadjourah': ['Tadjourah'],
      'Obock': ['Obock'],
    },
  },
  {
    code: 'ER', name: 'Eritrea', nameFr: 'Érythrée',
    currency: 'ERN', currencySymbol: 'Nfk', phonePrefix: '+291',
    timezone: 'Africa/Asmara', vatRate: 5, isOhada: false,
    regions: {
      'Asmara': ['Asmara'],
      'Gash-Barka': ['Barentu', 'Teseney'],
      'Debub': ['Mendefera', 'Adi Keyh'],
      'Anseba': ['Keren'],
      'Northern Red Sea': ['Massawa'],
    },
  },
  {
    code: 'SZ', name: 'Eswatini', nameFr: 'Eswatini',
    currency: 'SZL', currencySymbol: 'E', phonePrefix: '+268',
    timezone: 'Africa/Mbabane', vatRate: 15, isOhada: false,
    regions: {
      'Hhohho': ['Mbabane', 'Piggs Peak'],
      'Manzini': ['Manzini', 'Malkerns'],
      'Shiselweni': ['Nhlangano'],
      'Lubombo': ['Siteki'],
    },
  },
  {
    code: 'LS', name: 'Lesotho', nameFr: 'Lesotho',
    currency: 'LSL', currencySymbol: 'L', phonePrefix: '+266',
    timezone: 'Africa/Maseru', vatRate: 15, isOhada: false,
    regions: {
      'Maseru': ['Maseru', 'Teyateyaneng'],
      'Butha-Buthe': ['Butha-Buthe'],
      'Mafeteng': ['Mafeteng'],
      'Mohale\'s Hoek': ['Mohale\'s Hoek'],
      'Qacha\'s Nek': ['Qacha\'s Nek'],
      'Berea': ['Teyateyaneng'],
    },
  },
  {
    code: 'BW', name: 'Botswana', nameFr: 'Botswana',
    currency: 'BWP', currencySymbol: 'P', phonePrefix: '+267',
    timezone: 'Africa/Gaborone', vatRate: 14, isOhada: false,
    regions: {
      'Gaborone': ['Gaborone', 'Tlokweng'],
      'Francistown': ['Francistown'],
      'Kweneng': ['Molepolole'],
      'Kgalagadi': ['Tshabong'],
      'Central': ['Serowe', 'Palapye'],
      'Chobe': ['Kasane'],
    },
  },
  {
    code: 'NA', name: 'Namibia', nameFr: 'Namibie',
    currency: 'NAD', currencySymbol: 'N$', phonePrefix: '+264',
    timezone: 'Africa/Windhoek', vatRate: 15, isOhada: false,
    regions: {
      'Khomas': ['Windhoek'],
      'Erongo': ['Swakopmund', 'Walvis Bay'],
      'Oshana': ['Oshakati'],
      'Otjozondjupa': ['Otjiwarongo', 'Grootfontein'],
      'Karas': ['Keetmanshoop', 'Lüderitz'],
      'Hardap': ['Mariental'],
    },
  },
  {
    code: 'ZW', name: 'Zimbabwe', nameFr: 'Zimbabwe',
    currency: 'ZWL', currencySymbol: 'Z$', phonePrefix: '+263',
    timezone: 'Africa/Harare', vatRate: 15, isOhada: false,
    regions: {
      'Harare': ['Harare', 'Chitungwiza'],
      'Bulawayo': ['Bulawayo'],
      'Manicaland': ['Mutare', 'Chipinge'],
      'Mashonaland West': ['Chinhoyi'],
      'Masvingo': ['Masvingo'],
      'Midlands': ['Gweru', 'Kwekwe'],
    },
  },
  {
    code: 'ZM', name: 'Zambia', nameFr: 'Zambie',
    currency: 'ZMW', currencySymbol: 'K', phonePrefix: '+260',
    timezone: 'Africa/Lusaka', vatRate: 16, isOhada: false,
    regions: {
      'Lusaka': ['Lusaka', 'Kafue'],
      'Copperbelt': ['Ndola', 'Kitwe', 'Mufulira'],
      'Southern': ['Livingstone', 'Choma'],
      'Central': ['Kabwe', 'Kapiri Mposhi'],
      'Eastern': ['Chipata'],
      'Northern': ['Kasama', 'Mbala'],
    },
  },
  {
    code: 'MW', name: 'Malawi', nameFr: 'Malawi',
    currency: 'MWK', currencySymbol: 'K', phonePrefix: '+265',
    timezone: 'Africa/Blantyre', vatRate: 16.5, isOhada: false,
    regions: {
      'Lilongwe': ['Lilongwe'],
      'Blantyre': ['Blantyre', 'Limbe'],
      'Mzuzu': ['Mzuzu'],
      'Central': ['Kasungu', 'Dedza'],
      'Southern': ['Zomba', 'Mangochi'],
    },
  },
  {
    code: 'SL', name: 'Sierra Leone', nameFr: 'Sierra Leone',
    currency: 'SLL', currencySymbol: 'Le', phonePrefix: '+232',
    timezone: 'Africa/Freetown', vatRate: 15, isOhada: false,
    regions: {
      'Western Area': ['Freetown', 'Waterloo'],
      'Northern': ['Makeni', 'Kambia'],
      'Southern': ['Bo', 'Pujehun'],
      'Eastern': ['Kenema', 'Koidu'],
    },
  },
  {
    code: 'LR', name: 'Liberia', nameFr: 'Liberia',
    currency: 'LRD', currencySymbol: 'L$', phonePrefix: '+231',
    timezone: 'Africa/Monrovia', vatRate: 10, isOhada: false,
    regions: {
      'Montserrado': ['Monrovia', 'Paynesville', 'Brewerville'],
      'Nimba': ['Sanniquellie', 'Ganta'],
      'Bong': ['Gbarnga'],
      'Grand Bassa': ['Buchanan'],
      'Lofa': ['Voinjama'],
    },
  },
  {
    code: 'GM', name: 'Gambia', nameFr: 'Gambie',
    currency: 'GMD', currencySymbol: 'D', phonePrefix: '+220',
    timezone: 'Africa/Banjul', vatRate: 15, isOhada: false,
    regions: {
      'Banjul': ['Banjul'],
      'Kanifing': ['Serrekunda', 'Kanifing'],
      'Brikama': ['Brikama', 'Bakau'],
      'Farafenni': ['Farafenni'],
      'Basse': ['Basse Santa Su'],
    },
  },
  {
    code: 'GW', name: 'Guinea-Bissau', nameFr: 'Guinée-Bissau',
    currency: 'XOF', currencySymbol: 'FCFA', phonePrefix: '+245',
    timezone: 'Africa/Bissau', vatRate: 17, isOhada: true,
    regions: {
      'Bissau': ['Bissau'],
      'Bafatá': ['Bafatá'],
      'Gabú': ['Gabú'],
      'Cacheu': ['Cacheu', 'São Domingos'],
      'Oio': ['Farim', 'Mansôa'],
    },
  },
  {
    code: 'CV', name: 'Cape Verde', nameFr: 'Cap-Vert',
    currency: 'CVE', currencySymbol: '$', phonePrefix: '+238',
    timezone: 'Atlantic/Cape_Verde', vatRate: 15, isOhada: false,
    regions: {
      'Santiago': ['Praia', 'Assomada'],
      'São Vicente': ['Mindelo'],
      'Santo Antão': ['Ribeira Grande'],
      'Fogo': ['São Filipe'],
      'Sal': ['Santa Maria', 'Espargos'],
      'Boa Vista': ['Sal Rei'],
    },
  },
  {
    code: 'ST', name: 'São Tomé and Príncipe', nameFr: 'São Tomé-et-Príncipe',
    currency: 'STN', currencySymbol: 'Db', phonePrefix: '+239',
    timezone: 'Africa/Sao_Tome', vatRate: 15, isOhada: false,
    regions: {
      'São Tomé': ['São Tomé', 'Trindade'],
      'Príncipe': ['Santo António'],
    },
  },
  {
    code: 'SC', name: 'Seychelles', nameFr: 'Seychelles',
    currency: 'SCR', currencySymbol: 'SR', phonePrefix: '+248',
    timezone: 'Indian/Mahe', vatRate: 15, isOhada: false,
    regions: {
      'Mahé': ['Victoria', 'Anse Royale'],
      'Praslin': ['Grand\'Anse'],
      'La Digue': ['La Passe'],
    },
  },
  {
    code: 'MU', name: 'Mauritius', nameFr: 'Maurice',
    currency: 'MUR', currencySymbol: 'Rs', phonePrefix: '+230',
    timezone: 'Indian/Mauritius', vatRate: 15, isOhada: false,
    regions: {
      'Port Louis': ['Port Louis', 'Curepipe'],
      'Pamplemousses': ['Pamplemousses', 'Triolet'],
      'Flacq': ['Centre de Flacq', 'Bel Air'],
      'Plaines Wilhems': ['Quatre Bornes', 'Vacoas'],
      'Grand Port': ['Mahebourg', 'Rose-Belle'],
    },
  },
  {
    code: 'SO', name: 'Somalia', nameFr: 'Somalie',
    currency: 'SOS', currencySymbol: 'So.Sh.', phonePrefix: '+252',
    timezone: 'Africa/Mogadishu', vatRate: 5, isOhada: false,
    regions: {
      'Mogadishu': ['Mogadishu'],
      'Banaadir': ['Mogadishu'],
      'Somaliland': ['Hargeisa', 'Berbera'],
      'Puntland': ['Garowe', 'Bosaso'],
      'Bay': ['Baidoa'],
      'Shabeellaha Hoose': ['Merca'],
    },
  },
  {
    code: 'SS', name: 'South Sudan', nameFr: 'Soudan du Sud',
    currency: 'SSP', currencySymbol: '£', phonePrefix: '+211',
    timezone: 'Africa/Juba', vatRate: 15, isOhada: false,
    regions: {
      'Central Equatoria': ['Juba', 'Yei'],
      'Western Equatoria': ['Yambio', 'Maridi'],
      'Eastern Equatoria': ['Torit'],
      'Jonglei': ['Bor'],
      'Unity': ['Bentiu'],
      'Upper Nile': ['Malakal'],
    },
  },
  {
    code: 'SD', name: 'Sudan', nameFr: 'Soudan',
    currency: 'SDG', currencySymbol: '£S', phonePrefix: '+249',
    timezone: 'Africa/Khartoum', vatRate: 17, isOhada: false,
    regions: {
      'Khartoum': ['Khartoum', 'Omdurman', 'Bahri'],
      'Gezira': ['Wad Madani'],
      'Kassala': ['Kassala'],
      'Red Sea': ['Port Sudan', 'Suakin'],
      'Northern': ['Dongola'],
      'Darfur': ['Nyala', 'Al-Fashir'],
    },
  },
  {
    code: 'LY', name: 'Libya', nameFr: 'Libye',
    currency: 'LYD', currencySymbol: 'LD', phonePrefix: '+218',
    timezone: 'Africa/Tripoli', vatRate: 0, isOhada: false,
    regions: {
      'Tripoli': ['Tripoli', 'Tajoura'],
      'Benghazi': ['Benghazi'],
      'Misrata': ['Misrata'],
      'Zliten': ['Zliten'],
      'Sebha': ['Sebha'],
    },
  },
  {
    code: 'EH', name: 'Western Sahara', nameFr: 'Sahara occidental',
    currency: 'MAD', currencySymbol: 'MAD', phonePrefix: '+212',
    timezone: 'Africa/El_Aaiun', vatRate: 20, isOhada: false,
    regions: {
      'Laâyoune': ['Laâyoune', 'El Marsa'],
      'Dakhla': ['Dakhla'],
      'Es-Semara': ['Es-Semara'],
    },
  },
  {
    code: 'BI', name: 'Burundi', nameFr: 'Burundi',
    currency: 'BIF', currencySymbol: 'FBu', phonePrefix: '+257',
    timezone: 'Africa/Bujumbura', vatRate: 18, isOhada: true,
    regions: {
      'Bujumbura': ['Bujumbura'],
      'Bubanza': ['Bubanza'],
      'Gitega': ['Gitega'],
      'Ngozi': ['Ngozi'],
      'Muyinga': ['Muyinga'],
      'Ruyigi': ['Ruyigi'],
    },
  },
  {
    code: 'SH', name: 'Saint Helena', nameFr: 'Sainte-Hélène',
    currency: 'SHP', currencySymbol: '£', phonePrefix: '+290',
    timezone: 'Atlantic/St_Helena', vatRate: 0, isOhada: false,
    regions: {
      'Jamestown': ['Jamestown'],
    },
  },
  // Non-African expansion markets
  {
    code: 'FR', name: 'France', nameFr: 'France',
    currency: 'EUR', currencySymbol: '€', phonePrefix: '+33',
    timezone: 'Europe/Paris', vatRate: 20, isOhada: false,
    regions: {
      'Île-de-France': ['Paris', 'Boulogne-Billancourt', 'Montreuil'],
      'Auvergne-Rhône-Alpes': ['Lyon', 'Grenoble'],
      'Nouvelle-Aquitaine': ['Bordeaux', 'Libourne'],
      'Provence-Alpes-Côte d\'Azur': ['Marseille', 'Nice'],
      'Occitanie': ['Toulouse', 'Montpellier'],
      'Hauts-de-France': ['Lille', 'Roubaix'],
    },
  },
  {
    code: 'US', name: 'United States', nameFr: 'États-Unis',
    currency: 'USD', currencySymbol: '$', phonePrefix: '+1',
    timezone: 'America/New_York', vatRate: 0, isOhada: false,
    regions: {
      'New York': ['New York City', 'Buffalo'],
      'California': ['Los Angeles', 'San Francisco', 'San Diego'],
      'Texas': ['Houston', 'Dallas', 'Austin'],
      'Florida': ['Miami', 'Orlando', 'Tampa'],
      'Illinois': ['Chicago', 'Aurora'],
    },
  },
  {
    code: 'AE', name: 'United Arab Emirates', nameFr: 'Émirats arabes unis',
    currency: 'AED', currencySymbol: 'AED', phonePrefix: '+971',
    timezone: 'Asia/Dubai', vatRate: 5, isOhada: false,
    regions: {
      'Dubai': ['Dubai', 'Jebel Ali'],
      'Abu Dhabi': ['Abu Dhabi', 'Al Ain'],
      'Sharjah': ['Sharjah'],
      'Ajman': ['Ajman'],
      'Ras Al Khaimah': ['Ras Al Khaimah'],
    },
  },
  {
    code: 'GB', name: 'United Kingdom', nameFr: 'Royaume-Uni',
    currency: 'GBP', currencySymbol: '£', phonePrefix: '+44',
    timezone: 'Europe/London', vatRate: 20, isOhada: false,
    regions: {
      'England': ['London', 'Manchester', 'Birmingham'],
      'Scotland': ['Edinburgh', 'Glasgow'],
      'Wales': ['Cardiff'],
      'Northern Ireland': ['Belfast'],
    },
  },
  {
    code: 'CA', name: 'Canada', nameFr: 'Canada',
    currency: 'CAD', currencySymbol: 'C$', phonePrefix: '+1',
    timezone: 'America/Toronto', vatRate: 5, isOhada: false,
    regions: {
      'Ontario': ['Toronto', 'Ottawa', 'Mississauga'],
      'Quebec': ['Montreal', 'Quebec City'],
      'British Columbia': ['Vancouver', 'Victoria'],
      'Alberta': ['Calgary', 'Edmonton'],
    },
  },
  {
    code: 'DE', name: 'Germany', nameFr: 'Allemagne',
    currency: 'EUR', currencySymbol: '€', phonePrefix: '+49',
    timezone: 'Europe/Berlin', vatRate: 19, isOhada: false,
    regions: {
      'Berlin': ['Berlin'],
      'Bavaria': ['Munich', 'Nuremberg'],
      'Hesse': ['Frankfurt', 'Wiesbaden'],
      'Hamburg': ['Hamburg'],
    },
  },
  {
    code: 'CN', name: 'China', nameFr: 'Chine',
    currency: 'CNY', currencySymbol: '¥', phonePrefix: '+86',
    timezone: 'Asia/Shanghai', vatRate: 13, isOhada: false,
    regions: {
      'Beijing': ['Beijing'],
      'Shanghai': ['Shanghai'],
      'Guangdong': ['Guangzhou', 'Shenzhen'],
      'Zhejiang': ['Hangzhou', 'Ningbo'],
    },
  },
];

export const getCountryByCode = (code: string): CountryInfo | undefined =>
  COUNTRIES.find(c => c.code === code);

export const MODULES = [
  'dashboard', 'companies', 'chart_of_accounts', 'inventory', 'warehouses',
  'sales_invoices', 'purchase_invoices', 'transactions', 'ledger', 'reports',
  'banking', 'whatsapp', 'ai_cashflow', 'ohada', 'billing', 'settings',
  'users', 'roles', 'customers', 'suppliers',
  'credit_notes', 'bank_reconciliation', 'fixed_assets',
] as const;

export type ModuleKey = typeof MODULES[number];

export const PLAN_LIMITS: Record<string, ModuleKey[]> = {
  starter: ['dashboard', 'chart_of_accounts', 'inventory', 'warehouses', 'sales_invoices', 'purchase_invoices', 'customers', 'suppliers', 'transactions', 'ledger', 'reports', 'settings', 'users', 'roles', 'billing', 'companies', 'credit_notes'],
  pro: ['dashboard', 'chart_of_accounts', 'inventory', 'warehouses', 'sales_invoices', 'purchase_invoices', 'customers', 'suppliers', 'transactions', 'ledger', 'reports', 'banking', 'whatsapp', 'settings', 'users', 'roles', 'billing', 'companies', 'credit_notes', 'bank_reconciliation'],
  premium: ['dashboard', 'chart_of_accounts', 'inventory', 'warehouses', 'sales_invoices', 'purchase_invoices', 'customers', 'suppliers', 'transactions', 'ledger', 'reports', 'banking', 'whatsapp', 'ai_cashflow', 'ohada', 'settings', 'users', 'roles', 'billing', 'companies', 'credit_notes', 'bank_reconciliation', 'fixed_assets'],
  enterprise: ['dashboard', 'chart_of_accounts', 'inventory', 'warehouses', 'sales_invoices', 'purchase_invoices', 'customers', 'suppliers', 'transactions', 'ledger', 'reports', 'banking', 'whatsapp', 'ai_cashflow', 'ohada', 'settings', 'users', 'roles', 'billing', 'companies', 'credit_notes', 'bank_reconciliation', 'fixed_assets'],
};

export const COMMON_CURRENCIES = [
  { code: 'XAF', symbol: 'FCFA', name: 'Franc CFA (BEAC)' },
  { code: 'XOF', symbol: 'FCFA', name: 'Franc CFA (BCEAO)' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'NGN', symbol: '₦', name: 'Naira' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { code: 'GHS', symbol: '₵', name: 'Cedi' },
  { code: 'ZAR', symbol: 'R', name: 'Rand' },
  { code: 'ETB', symbol: 'Br', name: 'Birr' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
  { code: 'MAD', symbol: 'MAD', name: 'Dirham' },
  { code: 'TND', symbol: 'DT', name: 'Dinar Tunisien' },
  { code: 'DZD', symbol: 'DA', name: 'Dinar Algérien' },
  { code: 'CDF', symbol: 'FC', name: 'Franc Congolais' },
  { code: 'AOA', symbol: 'Kz', name: 'Kwanza' },
  { code: 'MZN', symbol: 'MT', name: 'Metical' },
  { code: 'UGX', symbol: 'USh', name: 'Shilling Ougandais' },
  { code: 'RWF', symbol: 'RF', name: 'Franc Rwandais' },
  { code: 'BIF', symbol: 'FBu', name: 'Franc Burundais' },
  { code: 'TZS', symbol: 'TSh', name: 'Shilling Tanzanien' },
  { code: 'ZMW', symbol: 'K', name: 'Kwacha Zambien' },
  { code: 'ZWL', symbol: 'Z$', name: 'Dollar Zimbabwéen' },
  { code: 'MWK', symbol: 'K', name: 'Kwacha Malawien' },
  { code: 'GNF', symbol: 'FG', name: 'Franc Guinéen' },
  { code: 'SLL', symbol: 'Le', name: 'Leone' },
  { code: 'LRD', symbol: 'L$', name: 'Dollar Libérien' },
  { code: 'GMD', symbol: 'D', name: 'Dalasi' },
  { code: 'DJF', symbol: 'FDj', name: 'Franc Djiboutien' },
  { code: 'ERN', symbol: 'Nfk', name: 'Nakfa' },
  { code: 'SZL', symbol: 'E', name: 'Lilangeni' },
  { code: 'LSL', symbol: 'L', name: 'Loti' },
  { code: 'BWP', symbol: 'P', name: 'Pula' },
  { code: 'NAD', symbol: 'N$', name: 'Dollar Namibien' },
  { code: 'SCR', symbol: 'SR', name: 'Roupie Seychelloise' },
  { code: 'MUR', symbol: 'Rs', name: 'Roupie Mauricienne' },
  { code: 'KMF', symbol: 'FC', name: 'Franc Comorien' },
  { code: 'STN', symbol: 'Db', name: 'Dobra' },
  { code: 'CVE', symbol: '$', name: 'Escudo Capverdien' },
  { code: 'SDG', symbol: '£S', name: 'Livre Soudanaise' },
  { code: 'SSP', symbol: '£', name: 'Livre Sud-Soudanaise' },
  { code: 'LYD', symbol: 'LD', name: 'Dinar Libyen' },
  { code: 'SOS', symbol: 'So.Sh.', name: 'Shilling Somalien' },
];

export const COMMON_TIMEZONES = [
  'Africa/Douala', 'Africa/Lagos', 'Africa/Nairobi', 'Africa/Accra',
  'Africa/Dakar', 'Africa/Abidjan', 'Africa/Cairo', 'Africa/Casablanca',
  'Africa/Tunis', 'Africa/Algiers', 'Africa/Kinshasa', 'Africa/Johannesburg',
  'Africa/Addis_Ababa', 'Africa/Kampala', 'Africa/Kigali', 'Africa/Bujumbura',
  'Africa/Maputo', 'Africa/Luanda', 'Africa/Brazzaville', 'Africa/Libreville',
  'Africa/Ndjamena', 'Africa/Bangui', 'Africa/Malabo', 'Africa/Niamey',
  'Africa/Ouagadougou', 'Africa/Bamako', 'Africa/Lome', 'Africa/Porto-Novo',
  'Africa/Conakry', 'Africa/Bissau', 'Africa/Freetown', 'Africa/Monrovia',
  'Africa/Banjul', 'Africa/Mbabane', 'Africa/Maseru', 'Africa/Gaborone',
  'Africa/Windhoek', 'Africa/Harare', 'Africa/Lusaka', 'Africa/Blantyre',
  'Africa/Dar_es_Salaam', 'Africa/Mogadishu', 'Africa/Juba', 'Africa/Khartoum',
  'Africa/Tripoli', 'Africa/El_Aaiun', 'Indian/Antananarivo', 'Indian/Mauritius',
  'Indian/Comoro', 'Indian/Mahe', 'Atlantic/Cape_Verde', 'Atlantic/St_Helena',
  'Europe/Paris', 'Europe/London', 'Europe/Berlin',
  'America/New_York', 'America/Toronto',
  'Asia/Dubai', 'Asia/Shanghai',
];
